version: '3'

services:

  node: 
    build:
      context: ./node
    container_name: node
    volumes:
      - ./node:usr/src/app
    tty: true
    ports:
      - "3000:3000"
    networks:
      - nodenet
    depends-on:
      - db

  nginx: 
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - nodenet
    ports: 
      - "8080:80"

   db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet

networks:
  nodenet: 
    driver: bridge